### PR TITLE
Set background-color on .wh-footer

### PR DESCRIPTION
**Pull request by lightswitch05**
Set `background-color: #FFFF;` on `.wh-footer` to prevent the side-bar from being viewed through the footer.
## Before

image
## After

image

### CODE REVIEW

**Comment by lightswitch05** [comment]
this bug still exists in production. To reproduce, go to the [petitions page](https://petitions.whitehouse.gov/petitions), and scroll to the very bottom. Depending on your window size, the sidebar on the right will be visible through the footer text. On laptop resolutions (1366x768) the bug will always be visible. On monitor resolutions (1280x1024) or larger, it is only noticeable if the browser window height is < 880px

**Comment by lightswitch05** [comment]
This still exists in production. Any word on why this hasn't been merged?

**Comment by fentie** [comment]
Confirmed this still exists on the site today. Any updates?

**Comment by lightswitch05** [comment]
looks like this was fixed by a javascript change

**Pull request closed without merging**
