### PR TITLE
Readability edits to readme.md

### PR DESCRIPTION
**Pull request by StevenBlack**
These edits 1) improve on-screen readability, 2) reduce hyperbole, and 3) add links to some of the assets referenced in the text.

Signed-off-by: Steven Black steveb@stevenblack.com

### CODE REVIEW

**Comment by StevenBlack** [comment]
maxwellhansen wrote:

> Is there anything wrong with hyperbole as it is used in the? To say the
> president simply wants a "more" open and "more" participatory government (as you
> do in your revision) is an understatement. Unless you have some reason to
> believe that the president explicitly does not support striving for the most
> open and participatory government in the world, I see nothing wrong with using
> "open" and "participatory" in their superlative forms to describe the
> aspirations of the current presidency.

The full snippet, as originally written, is
    `...the most open and participatory government in our nation’s history, ...`

The "in our nation's history" is hyperbole.  We have no basis for this claim; no measure for similar government initiatives through 236 years of history.

I remind you that we are led to believe, in lore and otherwise, that the founding of the Union was collaborative and participatory, among other legendary virtues.

I don't concede that "more" is an understatement.  The term `more` is a comparative that isn't subject, a-priori, to limits in amount or degree.

Therefore I believe that "more" is more appropriate than "most".

There's no mantle for claim here.  Despite evident progress in "open and participatory government", at this juncture it's merely getting better.  As it should.

Steven Black
(A Canadian with no horse in this race)

**Comment by Bastlynn** [comment]
Meh. Discussion re: which superlative to be used is rather pedantic. Let the work speak for itself in the coming years. Adding links and clarifying basic grammar (the "fully-MYSQL backed" fix for example) is good. Can you add return lines to bring the documentation to 80 column width?

**Comment by maxwellhansen** [comment]
Ah, Steven, I deleted that comment because I thought the argument about whether the superlative should be used was not very important. The problem with your adjustment is that the file is stating the president's opinion. If you think that the word 'most' is incorrect here, you can argue that the president's opinion is incorrect, but that does not mean we should misrepresent the opinion of the president to align better with what we think he should opine. Sorry if I am writing a bit incoherently.

**Comment by StevenBlack** [comment]
Closing this pull request.  Seeing zero activity in over tree weeks, this repo is apparently not active, or not actively led.  Either way...

**Pull request closed without merging**
