### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by JimiHFord**
This will make the license information show up in the repo's header on github

### CODE REVIEW

**Review by MarvinJWendt — CHANGES_REQUESTED** [review]
~There are many placeholders that aren't resolved to current names.~

~For example: 
`{project}  Copyright (C) {year}  {fullname}`
`{one line to give the program's name and a brief idea of what it does.}`
` Copyright (C) {year}  {name of author}`
Etc..~

**Comment by JimiHFord** [comment]
I believe that's how the license is supposed to be included. [This fairly popular GPL-3.0 project](https://github.com/netdata/netdata/blob/master/LICENSE#L655) contains these lines.

**Comment by MarvinJWendt** [comment]
Oh I see, my mistake, sorry.
Really thought that they should be replaced. I made a new license file in GitHub Web and it won´t replace those values too. So I guess you´re right!

Have a nice day :)

**Review by MarvinJWendt — APPROVED** [review]

**Comment by rbanffy** [comment]
Isn't everything done by the US government supposed to be public domain? If not, since this is a hosted app, I'd encourage the use of AGPL 3.0+ instead of plan GPL.

**Pull request closed without merging**
