### PR TITLE
Fixed few typos

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by christiangenco** [comment]
That was fast.

**Comment by greggles** [comment]
The changes to govdelivery should be provided as a patch to http://drupal.org/project/govdelivery

**Comment by pborreli** [comment]
@greggles thanks, i removed all the changes related to govdelivery.

**Comment by lheyman** [comment]
Thanks @pborreli

We cherry-picked your typo commits: ad350b5b8c032b206e1f0a014fe71be32cec0193, df42192d393b6187f517531182ab5d5801486d1a, a6cd8e89192dd7946d9448883c2ad5d6e932bc5d. 

As @greggles mentioned, the govdelivery updates should be contributed on the [govdelivery project page](http://drupal.org/project/govdelivery). We had to fork our own module a little, but we will take your commits under advisement when we update the module on drupal.org

[EDIT: changed commit SHA]

**Pull request closed without merging**
